export const START_GAME = 'APP/START_GAME';
export const FINISH_GAME = 'APP/FINISH_GAME';
export const INCREMENT_LEVEL = 'APP/INCREMENT_LEVEL';
export const UPDATE_KILL_COUNT = 'APP/UPDATE_KILL_COUNT';
