export const PREPARE_BULLET = 'PLAYER_BULLET/PREPARE_BULLET';
export const GENERATE = 'PLAYER_BULLET/GENERATE';
export const UPDATE = 'PLAYER_BULLET/UPDATE';
export const DELETE = 'PLAYER_BULLET/DELETE';
